hash-format = "sha256"

[[files]]
file = "config/create_connected-common.toml"
hash = "6bdf94e8a631d32ae4120156f00ea790583fca5ec81e58dd86eb36c113f63c47"

[[files]]
file = "config/immersive_optimization.json"
hash = "137299b6e13232a8b2aaaa1fb9a9a40da20a93065885d8a2d623573ea7bf2f86"

[[files]]
file = "config/rightclickharvest.json5"
hash = "3893db21c0bb5e3907e6ba5a1225f89686253b69d94bbb9008f4590e1260d441"

[[files]]
file = "config/tradingpost-server.toml"
hash = "8d66ca075a85ec8ff932e615179cced750487f13011e7f9568ccfe94a171dada"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bb30fd7ddb28a9b8ecd18f1ac6807509bd0facc8a6fa41a76ae5249f543d643d"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "1aaec67071b0a901b0b795292388261131b4d884ad846dc04c9c0653a620ca1d"
metafile = true

[[files]]
file = "mods/ante.pw.toml"
hash = "5da76c0eb70cdb063b3f87bcf8a2c8870a901f43a4d0f7e9539307e4381248ad"
metafile = true

[[files]]
file = "mods/anti-xray.pw.toml"
hash = "20c5254023ae6eaf0470d87a3e040e60f22b2109240f2e4a6ccc0227830d3981"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b2fd91a8a1185af60d7c051fcc4d6e179a7423899a85f931f03b9880edef09ea"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "d9973b1930e25c6599d1bfe718d2746b95e4ea11f96ad9b3158b8b3796f05812"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "9b3a8143b8b9371a24e2cf8e56295d96605863075ddd304c5e373aa44184d75f"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "c8b16a9466293917d779a51b05a3d7678d94c93c422c56369b3107b9aee72e37"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
hash = "a7767359ba82be952f8433852a86af034dd7a04cdc340a686c4591090647359b"
metafile = true

[[files]]
file = "mods/c2me-neoforge.pw.toml"
hash = "19181672c2b52ba7bbd39a7395d086d03213b719000a978c7934121166f44862"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "017707925596a68d683e0b2759b9df59a8fa34afce986a64f775507c672958e2"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "aa51c1af9869d9336e9fb9ae8c6ff182aa0f026ce34473ba8a142baa8e80cc06"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b0954d7cde7ac7d7c42e645b0f3f346e9315b3d276acfb4d62280524614a7213"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "fe127a6927e3b15b8503102cf377efb25f1eac5a110997003cb06e123ad210d8"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "592f8b93dd46bd16e154fe149af1e26465104e070863e4748f5fe439fc365d2e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "8c87fffa96f44b1c3cadbb1e5589e3a32d4c77720dedbf26f20dcbcdb9607a62"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "e16984cdb425e93c40cf797b99cfe92da31092ebe72c4e9c4f5fbccbc10cfcff"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
hash = "47f58e11558cefa4116b82c72689ebb87957e38fcfa558b53bdefc6a5a5963f4"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "dbb78d58cc5061319a0aa4f784b9ec9ffcac5c0225394cc7674a616f951711d3"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "2b35efd05a2a9e48140e5381d133d8a9ce39c0787c959d4d00064aad66953ac8"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "65d754fe568579849066ca26ea7acebb0d485ebe5103da2eab517f11ddcd1fc4"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "102b88ab1cf48a8140baffdfb486bb19001b2cb0413c7b5b3ea5a6edc3a01794"
metafile = true

[[files]]
file = "mods/craftinuum.pw.toml"
hash = "b4e1362d83b0ed9891c0210b16bf36509f6edbfbb30e9d1768db8a30fa59597d"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "0dfb8af5ad6b9b836662916392da879c518f011ffbf44e109225f11621ffbdab"
metafile = true

[[files]]
file = "mods/create-copper-zinc.pw.toml"
hash = "8a559d318ebf0a01bc21fd017736b0c322d07c5ba3654eeba961aed8f615c2f3"
metafile = true

[[files]]
file = "mods/create-curios-jetpack.pw.toml"
hash = "7b049d04ea40b814613b83bfa6125ca91da08607f509c70dbb9cf83e996d4172"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "63e739899478a9490e43da15bea4fbf8e6e135acae39865b8060f0d37268fd34"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "f070d930d2516afb8adb1784e3123bc21b10eec28c23901340434a47bc109ca8"
metafile = true

[[files]]
file = "mods/create-liquid-fuel.pw.toml"
hash = "942afb11a1a534ef844930b7518aa0a7e254b4ea9898f9f164120e2f46d5b00c"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "4fe55dfb230a5072fc976387e179526e7bb512f79c7d71aa3da80b59420b7a27"
metafile = true

[[files]]
file = "mods/create-stone-generators.pw.toml"
hash = "922f90815b0678844f4fc266cd0bbf86de79315c2b726c4c551c4f76bb25dc4a"
metafile = true

[[files]]
file = "mods/create-stones.pw.toml"
hash = "b648c04c04d2f57e7cf4ba869078ba3b2ca76430c38aded91f55af1ec6c5d92e"
metafile = true

[[files]]
file = "mods/create-trading-floor.pw.toml"
hash = "90f3be8276c29252c4e96d3a57854b70179a6c9a524edf3a1549db3bfc19b473"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "f079c74a261e805cf5655d79414125f7744cf1f9a888bd4ff86a6e014ad364f8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "29b81fd0e463f7eeb5b92c1e633f16a562d340bb1ec71f65a80524d2389edb03"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
hash = "2ba68fa5010b25f030dc10efcbb76a165f457e1fef5263f0a57304e26f833f34"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "128923d7b4681d796c29162be2c592e54cd62d68f76a87e58f6f10a1a71149f0"
metafile = true

[[files]]
file = "mods/dragonkind-evolved.pw.toml"
hash = "1844621ce64f69eb40c9cfe2d4f8f8730d46a00464bab615ec2d2fe39659fd54"
metafile = true

[[files]]
file = "mods/dripsounds.pw.toml"
hash = "503a0a426185206fe456574b424066bc4c93ad86319b7356bbc5ae3319cc52d1"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "505b920d5efddcc0c45857de75823f7da9a2d8d6467dee280bc64131b51fd949"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "3fbaafd070ce6c2eaccb00410decc13e2340ff63e0373b3bd06bc59ec921a647"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ed0df341b329ff3c943235cfc894cd475a05933d1fed6c3dca819e51ce253630"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "3931194da703e949f57f242f4f40f17e3a3aaf25dcb9df861b07502f80a2b02f"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "c4027b8071cc6dfc7f0d49e702a5e25b1e36841e50acba1e699f308be156b8f2"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "2756ce49983f6f003b8cc82e6241cb0589e39b5ae819083f4e3d7cebad3e26bf"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "d8ce32a3f2d6245e77ba87a7c8741c3673399d958a529b6f8bf2ff35cd0bb277"
metafile = true

[[files]]
file = "mods/flames-create-netherrack.pw.toml"
hash = "d5b5cf77f880fc5c6ae1758884b86c6c0607c5e92f6049b3da7e6b80365dde5f"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "7e2b59817638c256e22b5dc11d93017b2ce32241ec1e97dd067e19395aa24d03"
metafile = true

[[files]]
file = "mods/grieflogger.pw.toml"
hash = "91ac310d8536931e35ca489098f8f78b42ecf0ea4527a94a9abed92a2fe4ad9e"
metafile = true

[[files]]
file = "mods/hide-experimental-warning.pw.toml"
hash = "7fa8a7e71b978fe0e9e3d9bef29ad8e96f3a463936dc663b5f2d4821fa35e31f"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "c662baa4e0747b23fbdd4e375ee93b4071c88de771ae9fdcc58a2045a6ac356a"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "788d07070c5eb8924d1fde9138edce229cb4ce5834489817c860f35cbd802b05"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
hash = "f6ebebf2fecd990cc51792fce4eeeade28d224572fee0df230cfa3b961d74c3e"
metafile = true

[[files]]
file = "mods/inv-view-forge.pw.toml"
hash = "a40e68d8848a871a5d53ebbc5c73db8cc1dfe76273a6bcef2a0e0d4d8b9299d8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "db4a43961cb5ab823da0e27fbe5487a7e277a61cee5c194f42e1edcc498dfe0d"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "bcb16b9eb7c88613eefdaab5820613f0361cf505f6eca71a33b729b7e19a80fd"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "fe90b0672c7842cef05e9e200126d9fbb3c930c6bd175b9aaf8ed5bedc32dea7"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "d957d6d8ab5d1fa4acf0aa29d341e9cdb642fcea1e37239e137e27c10eeb7e4b"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b5f4ce331c81f7fcde8224a01de305cfe08ab5aa2dd64e5884898e569ef03a0e"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "a5f5aa9e76f2bb2418836421efde235b6bd6e664ae3ba18c1b2da4d18fdc04e8"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "3366f46869c1de1e66d6fe6aaf29cf338c080fbf1d786e7111f445d76885c4c6"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "39d7f5b7e99a9469aca4844a7987586c472fd34cc73ba63de138694668ad4086"
metafile = true

[[files]]
file = "mods/longer-chat-history.pw.toml"
hash = "b6105d9b7f77112f6cf69029f659b3e5e7ac07e0c049fadeb8ad9e196364c202"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "cda7b1d997fa04b822b723f5ec453e9c128402b4ed02c87b2bc4595f89b635e7"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "29f27629382cf2765e9ce66e7b135b1e5d688ec9bba66e44abd832947af0375b"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "5c1820d0d8504da6e1cf27ca964101435633187c2e1bb8363d1891aace00f58a"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "f510b143e3bd823f8337e6bf8736fdcb02454adf457595eb40380740c4d1b683"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "b0561741381aa3db185ad9e1c7f0f626ba0809bf115270b854aa64606e642147"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "32157b6f2b2d55bec2575281a39fc262870468727bd396379d02bf54d6325034"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "0024f11292a5cb244107fa2b91dbee9ccb02bcc62b82ad74ec460523c219febe"
metafile = true

[[files]]
file = "mods/ore-harvester.pw.toml"
hash = "2049bf5d5c412a0673b9405869a1fb65d8a9f7a806cf1f41b512cdfe9e46a643"
metafile = true

[[files]]
file = "mods/our-villager-discounts.pw.toml"
hash = "c0b251fc69be65a0dd61e6961694fac4b0d78ca33a586e06359d084a49e93b1f"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "6719083345bde635cd6048d8438f75eef56937c3b5438c1294e382ba52bf5c02"
metafile = true

[[files]]
file = "mods/player-trade.pw.toml"
hash = "3ea812a9641dd774c294e341ae31ea91c81ccc09a6932b71f0c6b41b15e66e70"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "7ffbc9f4356e44a7f1e94183cfa62a9a62217a5f5a0ef2962692379895c82d23"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "752773846c8f80da884986250f5d4e190ae7972d0938c8de3178bf03053d5b9c"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "0b38c685b950027a8cd5da444425e9a153bc96a3b97c4fe0868c43bf490f66d3"
metafile = true

[[files]]
file = "mods/server-chat-sync.pw.toml"
hash = "340561af9120d3fce0b5fcb56b97f234bd0b7fef752ffa3c77580b93ab2ea679"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "89b1cca7036422743ca2d7e8fbc0ce1c73b0d042f97ba99e494869734610508a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "800d02cae713c24df51915c86943e5873414e2d74ac1b033db2159590d61a9b4"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a2897c9039fd559d387978ee4b7153f8e17909fa1ed229af994166958399a2e4"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "49d48cbe1453c185cc4eb55527e9f5ff933221c15e3441d229cda11c56781e0e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "600c425ced8b555cec6e0e5ec4628a794b6b08e478c165b20ca930c0d44b9079"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be6f9f60b705e1be3722b3cef7d8d6c4a16fb31f0cad0efdcca83636ec1271b"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "62bd7012826fdcccf17a089055be67f87fb7335c88e73efc52bc9e51a1bf3188"
metafile = true

[[files]]
file = "mods/too-fast.pw.toml"
hash = "908fca687ac9e17434c76639ced72db1e7f089b00a92a4b60b2a0f0a8c65240a"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "d3d9b3b1ebda272350fae769b1f9b2f3fec6740186030bb62822dca35bf0ac42"
metafile = true

[[files]]
file = "mods/trading-post.pw.toml"
hash = "01b4c667ff0aef28efe5a3e2d3bb70e0e33444488948ad6410a07eaf8022e283"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "1e81c07bc5141bf1e5773a791b748fbdf354866edb32d55e04f19fea4ae526a1"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "0c8909d81a5e6143f21d14fc343d33d26315058e4508b61911960bb7b476f379"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "7349be2ec197fca8767bb4a203f48c23f6762bb2bc1954110e355d7feb541e8e"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "a82432f5c27d4f6a0e34c6600db1950f7330331babee2b0d1f5ca45cbd750138"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "15d8d5dd41f3c367dd5c82f47989f033cb83ef7cd40858ed1545ab76788eb4ce"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "1fa402a3897fd1c60b703e4ae6c212d8a568af873750f71da750332dfac11cf3"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "ef2e3ee06cad79f9c6d73902a796716489c1993f11805046e8fbf8d9aa03b027"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "5a687d30e61482686b873a1f72dc51352a93606234c8a86369eeb8826764d4a6"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "06b2831bfe1a9c84eb45308793abde45bc610bdc7d3839260de6e2779bd372ec"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "566f02883599153cc907c0a213f0a315b37ec4fd245a0a1e5d267510cbee1ebb"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "17af97debf219cc2739b7004fdabc605182ed916410b5aaa982f405e07869cf5"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "887ced44e054d9fb0901c31833ec17f4b22a66c3f1f484df9ae01b00f2609534"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "a43a041fa8670cae6f919f49d6844b4e536fb37fc77910e2dcb06a45a78065f6"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "f39076993b1cd629f7e7db358383f5cdfd5f8cf4d41db2120e1ed659d8b1e161"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "83496042d1f17d08a645522190089c52ab8efafd5e0fe6f425df98411d276f96"
metafile = true

[[files]]
file = "world/datapacks/blazeandcaves-advancements-pack.pw.toml"
hash = "abe2fe522534c6c0dfb5f81e8e6273ac0f74190759f6b6e257f14aba1ec70a4f"
metafile = true
