name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4170b26e9aa7b84f5171617b1b888f321417e78a040994daafdf5727155f4bae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
