name = "Minceraft S4"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4900b06ee6830a9943cba6ced7db19b228861c400cad8bb383107ff41bea3c7b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.179"
