name = "Denise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97df67d6bfdd93cdf0507bb854cb1f35c2804d5984034456843c8f06eb95fd66"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
