name = "Denise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e9e6a747deba15d865ee29c1ad678fa99b595678c86f24c6734a6aaf4fad4f3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
