name = "Denise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89bb4d1125092ecbc6371a3e4de6d9d262a973ff1890b8d92fb586a55ae7b664"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
