name = "Minceraft Season 5"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1f129fd0f467d703fadc82adf0ac8e457fc5745e6dba91f1a7bc9c4fa8fd007"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
