name = "Minceraft Season 5"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeddd903e49da89d96b10de2edfa2740d2b9b4d9b7b94d28132aebd9ccf9fda9"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
