name = "Minceraft Season 5"
author = "robieless"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57c16106dfbf2759172c817a7a8ff60d5e4f1e1c00d9f5a7ab6a2bae3b05c582"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
